service: myklan-task-notifications

custom:
  secrets: ${file(../../secrets.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}
    GOOGLE_CLIENT_ID: ${self:custom.secrets.GOOGLE_CLIENT_ID}
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGW-rootResourceId

package:
  include:
    - ../../lib/**
    - ../../node_modules/**

functions:
  task-verify-token:
    handler: lib/utils/verify-token.auth
          
  addTask:
    handler: task/task-handler.addTask
    events:
      - http:
          path: taskNotifications/addTask
          method: post
          cors: true
          authorizer: task-verify-token
          
  notifyMembers:
    handler: task/task-handler.notifyMembers
    events:
      - http:
          path: taskNotifications/notifyMembers
          method: post
          cors: true
          authorizer: task-verify-token
          
  updateTask:
    handler: task/task-handler.updateTask
    events:
      - http:
          path: taskNotifications/updateTask
          method: post
          cors: true
          authorizer: task-verify-token
          
  getTasks:
    handler: task/task-handler.getTasks
    events:
      - http:
          path: taskNotifications/getTasks
          method: get
          cors: true
          authorizer: task-verify-token
          
  deleteTask:
    handler: task/task-handler.deleteTask
    events:
      - http:
          path: taskNotifications/deleteTask
          method: delete
          cors: true
          authorizer: task-verify-token