service: myklan-shared-space

custom:
  secrets: ${file(../../secrets.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}
    GOOGLE_CLIENT_ID: ${self:custom.secrets.GOOGLE_CLIENT_ID}
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGW-rootResourceId

package:
  include:
    - ../../lib/**
    - ../../node_modules/**

functions:
  shared-verify-token:
    handler: lib/utils/verify-token.auth
          
  addAccount:
    handler: account/account-handler.addAccount
    events:
      - http:
          path: sharedSpace/addAccount
          method: post
          cors: true
          authorizer: shared-verify-token
          
  updateAccount:
    handler: account/account-handler.updateAccount
    events:
      - http:
          path: sharedSpace/updateAccount
          method: post
          cors: true
          authorizer: shared-verify-token
          
  getAccounts:
    handler: account/account-handler.getAccounts
    events:
      - http:
          path: sharedSpace/getAccounts
          method: get
          cors: true
          authorizer: shared-verify-token
          
  deleteAccount:
    handler: account/account-handler.deleteAccount
    events:
      - http:
          path: sharedSpace/deleteAccount
          method: delete
          cors: true
          authorizer: shared-verify-token
          
  addContact:
    handler: contact/contact-handler.addContact
    events:
      - http:
          path: sharedSpace/addContact
          method: post
          cors: true
          authorizer: shared-verify-token
          
  updateContact:
    handler: contact/contact-handler.updateContact
    events:
      - http:
          path: sharedSpace/updateContact
          method: post
          cors: true
          authorizer: shared-verify-token
          
  getContacts:
    handler: contact/contact-handler.getContacts
    events:
      - http:
          path: sharedSpace/getContacts
          method: get
          cors: true
          authorizer: shared-verify-token
          
  deleteContact:
    handler: contact/contact-handler.deleteContact
    events:
      - http:
          path: sharedSpace/deleteContact
          method: delete
          cors: true
          authorizer: shared-verify-token